# product-service
services:
  product-service:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - product_service_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    command: yarn start:debug
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
    networks:
      - message_broker_network

volumes:
  product_service_modules:

networks:
  message_broker_network:
    external: true
