services:
  product-service:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229' # Debug port
    command: npm run start:debug
    environment:
      - NODE_ENV=development
    networks:
      - message_broker_network

networks:
  message_broker_network:
    external: true
